### ISSUE TITLE
typo in project description

### ISSUE THREAD

**Issue by damned** [Rooster212/DotNetStandardCalculator#14]
mathmatical -  should be mathematical :)

**Comment by damned** [comment]
when i say project description i mean github repo description

**Comment by Rooster212** [comment]
Thanks! I'll fix it later, but feel free to put a pull request in yourself if you like.

**Comment by damned** [comment]
not sure how to / if i can issue pull request for repo description :/

**Comment by Rooster212** [comment]
Fixed in 1d62264
